site_name: Doorstop
site_description: Requirements management using version control.
site_author: Jace Browning

repo_url: https://github.com/doorstop-dev/doorstop
edit_uri: https://github.com/doorstop-dev/doorstop/edit/develop/docs

theme: readthedocs

markdown_extensions:
  - admonition
use_directory_urls: false
hooks:
 - docs/generate.py

nav:
- Home: index.md
- Getting Started:
  - Installation: getting-started/installation.md
  - Setup: getting-started/setup.md
  - Quickstart: getting-started/quickstart.md
- Command-line Interface:
  - Creating Documents: cli/creation.md
  - Reordering Documents: cli/reordering.md
  - Validating Requirements: cli/validation.md
  - Publishing Documents: cli/publishing.md
  - Importing and Exporting: cli/interchange.md
- Interfaces:
  - Desktop Client: gui/overview.md
  - Web Server: web.md
  - Scripting API: api/scripting.md
- Reference:
  - Tree: reference/tree.md
  - Document: reference/document.md
  - Item: reference/item.md
- Examples:
  - 3rd-Party Projects: examples.md
  - Doorstop's Requirements: gen/index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
